# Form implementation generated from reading ui file './DetectorLocationDialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(252, 212)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 130, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 20, 160, 85))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.x_label = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.x_label.setObjectName("x_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.x_label)
        self.x_text = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.x_text.setObjectName("x_text")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.x_text)
        self.y_text = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.y_text.setObjectName("y_text")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.y_text)
        self.y_label = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.y_label.setObjectName("y_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.y_label)
        self.z_label = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.z_label.setObjectName("z_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.z_label)
        self.z_text = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.z_text.setObjectName("z_text")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.z_text)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Detector Location"))
        self.x_label.setText(_translate("Dialog", "X (cm):"))
        self.x_text.setPlaceholderText(_translate("Dialog", "0.0"))
        self.y_text.setPlaceholderText(_translate("Dialog", "0.0"))
        self.y_label.setText(_translate("Dialog", "Y (cm):"))
        self.z_label.setText(_translate("Dialog", "Z (cm):"))
        self.z_text.setPlaceholderText(_translate("Dialog", "0.0"))
