# Form implementation generated from reading ui file 'GraphicsDialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GraphicsDialog(object):
    def setupUi(self, GraphicsDialog):
        GraphicsDialog.setObjectName("GraphicsDialog")
        GraphicsDialog.resize(548, 465)
        self.verticalLayout = QtWidgets.QVBoxLayout(GraphicsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.display_view = QtInteractor(parent=GraphicsDialog)
        self.display_view.setObjectName("display_view")
        self.verticalLayout.addWidget(self.display_view)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=GraphicsDialog)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(parent=GraphicsDialog)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(GraphicsDialog)
        QtCore.QMetaObject.connectSlotsByName(GraphicsDialog)

    def retranslateUi(self, GraphicsDialog):
        _translate = QtCore.QCoreApplication.translate
        GraphicsDialog.setWindowTitle(_translate("GraphicsDialog", "View of the Model"))
        self.pushButton.setText(_translate("GraphicsDialog", "OK"))
from pyvistaqt import QtInteractor
