# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.11.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenu, QMenuBar,
    QScrollArea, QSizePolicy, QStatusBar, QTextEdit,
    QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        self.actionRemove = QAction(MainWindow)
        self.actionRemove.setObjectName(u"actionRemove")
        self.actionRemove.setEnabled(False)
        self.actionBuildup_Material = QAction(MainWindow)
        self.actionBuildup_Material.setObjectName(u"actionBuildup_Material")
        self.actionDaughters = QAction(MainWindow)
        self.actionDaughters.setObjectName(u"actionDaughters")
        self.actionEnergy_Groups = QAction(MainWindow)
        self.actionEnergy_Groups.setObjectName(u"actionEnergy_Groups")
        self.actionPython_Script = QAction(MainWindow)
        self.actionPython_Script.setObjectName(u"actionPython_Script")
        self.actionGraphics = QAction(MainWindow)
        self.actionGraphics.setObjectName(u"actionGraphics")
        self.location = QAction(MainWindow)
        self.location.setObjectName(u"location")
        self.actionZapMeNot_Help = QAction(MainWindow)
        self.actionZapMeNot_Help.setObjectName(u"actionZapMeNot_Help")
        self.actionAbout_ZapMeNot = QAction(MainWindow)
        self.actionAbout_ZapMeNot.setObjectName(u"actionAbout_ZapMeNot")
        self.actionSemiInfiniteShield = QAction(MainWindow)
        self.actionSemiInfiniteShield.setObjectName(u"actionSemiInfiniteShield")
        self.actionSemiInfiniteXSlab = QAction(MainWindow)
        self.actionSemiInfiniteXSlab.setObjectName(u"actionSemiInfiniteXSlab")
        self.actionSphere = QAction(MainWindow)
        self.actionSphere.setObjectName(u"actionSphere")
        self.actionShell = QAction(MainWindow)
        self.actionShell.setObjectName(u"actionShell")
        self.actionBox = QAction(MainWindow)
        self.actionBox.setObjectName(u"actionBox")
        self.actionInfiniteAnnulus = QAction(MainWindow)
        self.actionInfiniteAnnulus.setObjectName(u"actionInfiniteAnnulus")
        self.actionXAlignedInfiniteAnnulus = QAction(MainWindow)
        self.actionXAlignedInfiniteAnnulus.setObjectName(u"actionXAlignedInfiniteAnnulus")
        self.actionYAlignedInfiniteAnnulus = QAction(MainWindow)
        self.actionYAlignedInfiniteAnnulus.setObjectName(u"actionYAlignedInfiniteAnnulus")
        self.actionZAlignedInfiniteAnnulus = QAction(MainWindow)
        self.actionZAlignedInfiniteAnnulus.setObjectName(u"actionZAlignedInfiniteAnnulus")
        self.actionCappedCylinder = QAction(MainWindow)
        self.actionCappedCylinder.setObjectName(u"actionCappedCylinder")
        self.actionLine_Source = QAction(MainWindow)
        self.actionLine_Source.setObjectName(u"actionLine_Source")
        self.actionPoint_Source = QAction(MainWindow)
        self.actionPoint_Source.setObjectName(u"actionPoint_Source")
        self.actionSpherical_Source = QAction(MainWindow)
        self.actionSpherical_Source.setObjectName(u"actionSpherical_Source")
        self.actionBox_Source = QAction(MainWindow)
        self.actionBox_Source.setObjectName(u"actionBox_Source")
        self.actionX_Aligned_Cylinder_Source = QAction(MainWindow)
        self.actionX_Aligned_Cylinder_Source.setObjectName(u"actionX_Aligned_Cylinder_Source")
        self.actionY_Aligned_Cylinder_Source = QAction(MainWindow)
        self.actionY_Aligned_Cylinder_Source.setObjectName(u"actionY_Aligned_Cylinder_Source")
        self.actionZ_Aligned_Cylinder_Source = QAction(MainWindow)
        self.actionZ_Aligned_Cylinder_Source.setObjectName(u"actionZ_Aligned_Cylinder_Source")
        self.actionBy_Isotope = QAction(MainWindow)
        self.actionBy_Isotope.setObjectName(u"actionBy_Isotope")
        self.actionBy_Energy = QAction(MainWindow)
        self.actionBy_Energy.setObjectName(u"actionBy_Energy")
        self.actionImport = QAction(MainWindow)
        self.actionImport.setObjectName(u"actionImport")
        self.actionQuadrature = QAction(MainWindow)
        self.actionQuadrature.setObjectName(u"actionQuadrature")
        self.actionX_Aligned_Cylinder = QAction(MainWindow)
        self.actionX_Aligned_Cylinder.setObjectName(u"actionX_Aligned_Cylinder")
        self.actionY_Aligned_Cylinder = QAction(MainWindow)
        self.actionY_Aligned_Cylinder.setObjectName(u"actionY_Aligned_Cylinder")
        self.actionZ_Aligned_Cylinder = QAction(MainWindow)
        self.actionZ_Aligned_Cylinder.setObjectName(u"actionZ_Aligned_Cylinder")
        self.actionFiller_Material = QAction(MainWindow)
        self.actionFiller_Material.setObjectName(u"actionFiller_Material")
        self.actionQuadrature_2 = QAction(MainWindow)
        self.actionQuadrature_2.setObjectName(u"actionQuadrature_2")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 774, 518))
        self.verticalLayout_2 = QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.summaryDescription = QTextEdit(self.scrollAreaWidgetContents)
        self.summaryDescription.setObjectName(u"summaryDescription")
        self.summaryDescription.setReadOnly(True)

        self.verticalLayout_2.addWidget(self.summaryDescription)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.verticalLayout.addWidget(self.scrollArea)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 29))
        self.menu_Source = QMenu(self.menubar)
        self.menu_Source.setObjectName(u"menu_Source")
        self.menuBody = QMenu(self.menu_Source)
        self.menuBody.setObjectName(u"menuBody")
        self.menuPhotons = QMenu(self.menu_Source)
        self.menuPhotons.setObjectName(u"menuPhotons")
        self.menuShield = QMenu(self.menubar)
        self.menuShield.setObjectName(u"menuShield")
        self.menuAdd = QMenu(self.menuShield)
        self.menuAdd.setObjectName(u"menuAdd")
        self.menuDetector = QMenu(self.menubar)
        self.menuDetector.setObjectName(u"menuDetector")
        self.menuOptions = QMenu(self.menubar)
        self.menuOptions.setObjectName(u"menuOptions")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menu_Source.menuAction())
        self.menubar.addAction(self.menuShield.menuAction())
        self.menubar.addAction(self.menuDetector.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menu_Source.addAction(self.menuBody.menuAction())
        self.menu_Source.addAction(self.menuPhotons.menuAction())
        self.menuBody.addAction(self.actionLine_Source)
        self.menuBody.addAction(self.actionPoint_Source)
        self.menuBody.addAction(self.actionSpherical_Source)
        self.menuBody.addAction(self.actionBox_Source)
        self.menuBody.addAction(self.actionX_Aligned_Cylinder_Source)
        self.menuBody.addAction(self.actionY_Aligned_Cylinder_Source)
        self.menuBody.addAction(self.actionZ_Aligned_Cylinder_Source)
        self.menuPhotons.addAction(self.actionBy_Isotope)
        self.menuPhotons.addAction(self.actionBy_Energy)
        self.menuPhotons.addAction(self.actionImport)
        self.menuShield.addAction(self.menuAdd.menuAction())
        self.menuShield.addAction(self.actionRemove)
        self.menuAdd.addAction(self.actionSemiInfiniteXSlab)
        self.menuAdd.addAction(self.actionSphere)
        self.menuAdd.addAction(self.actionBox)
        self.menuAdd.addAction(self.actionInfiniteAnnulus)
        self.menuAdd.addAction(self.actionXAlignedInfiniteAnnulus)
        self.menuAdd.addAction(self.actionYAlignedInfiniteAnnulus)
        self.menuAdd.addAction(self.actionZAlignedInfiniteAnnulus)
        self.menuAdd.addAction(self.actionCappedCylinder)
        self.menuAdd.addAction(self.actionX_Aligned_Cylinder)
        self.menuAdd.addAction(self.actionY_Aligned_Cylinder)
        self.menuAdd.addAction(self.actionZ_Aligned_Cylinder)
        self.menuDetector.addAction(self.location)
        self.menuOptions.addAction(self.actionBuildup_Material)
        self.menuOptions.addAction(self.actionDaughters)
        self.menuOptions.addAction(self.actionEnergy_Groups)
        self.menuOptions.addAction(self.actionFiller_Material)
        self.menuOptions.addAction(self.actionQuadrature_2)
        self.menuView.addAction(self.actionPython_Script)
        self.menuView.addAction(self.actionGraphics)
        self.menuHelp.addAction(self.actionZapMeNot_Help)
        self.menuHelp.addAction(self.actionAbout_ZapMeNot)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"ZapMeNot", None))
        self.actionRemove.setText(QCoreApplication.translate("MainWindow", u"Remove ...", None))
        self.actionBuildup_Material.setText(QCoreApplication.translate("MainWindow", u"Buildup Material ...", None))
        self.actionDaughters.setText(QCoreApplication.translate("MainWindow", u"Daughters ...", None))
        self.actionEnergy_Groups.setText(QCoreApplication.translate("MainWindow", u"Energy Groups ...", None))
        self.actionPython_Script.setText(QCoreApplication.translate("MainWindow", u"Python Script", None))
        self.actionGraphics.setText(QCoreApplication.translate("MainWindow", u"Graphics", None))
        self.location.setText(QCoreApplication.translate("MainWindow", u"Location ...", None))
        self.actionZapMeNot_Help.setText(QCoreApplication.translate("MainWindow", u"ZapMeNot Help", None))
        self.actionAbout_ZapMeNot.setText(QCoreApplication.translate("MainWindow", u"About ZapMeNot", None))
        self.actionSemiInfiniteShield.setText(QCoreApplication.translate("MainWindow", u"Semi-Infinite Shield", None))
        self.actionSemiInfiniteXSlab.setText(QCoreApplication.translate("MainWindow", u"Semi-Infinite X-Aligned Slab", None))
        self.actionSphere.setText(QCoreApplication.translate("MainWindow", u"Sphere", None))
        self.actionShell.setText(QCoreApplication.translate("MainWindow", u"Shell", None))
        self.actionBox.setText(QCoreApplication.translate("MainWindow", u"Box", None))
        self.actionInfiniteAnnulus.setText(QCoreApplication.translate("MainWindow", u"Infinite Annulus", None))
        self.actionXAlignedInfiniteAnnulus.setText(QCoreApplication.translate("MainWindow", u"X-Aligned Infinite Annulus", None))
        self.actionYAlignedInfiniteAnnulus.setText(QCoreApplication.translate("MainWindow", u"Y-Aligned Infinte Annulus", None))
        self.actionZAlignedInfiniteAnnulus.setText(QCoreApplication.translate("MainWindow", u"Z-Aligned Infinite Annulus", None))
        self.actionCappedCylinder.setText(QCoreApplication.translate("MainWindow", u"Capped Cylinder", None))
        self.actionLine_Source.setText(QCoreApplication.translate("MainWindow", u"Line Source", None))
        self.actionPoint_Source.setText(QCoreApplication.translate("MainWindow", u"Point Source", None))
        self.actionSpherical_Source.setText(QCoreApplication.translate("MainWindow", u"Spherical Source", None))
        self.actionBox_Source.setText(QCoreApplication.translate("MainWindow", u"Box Source", None))
        self.actionX_Aligned_Cylinder_Source.setText(QCoreApplication.translate("MainWindow", u"X-Aligned Cylinder Source", None))
        self.actionY_Aligned_Cylinder_Source.setText(QCoreApplication.translate("MainWindow", u"Y-Aligned Cylinder Source", None))
        self.actionZ_Aligned_Cylinder_Source.setText(QCoreApplication.translate("MainWindow", u"Z-Aligned Cylinder Source", None))
        self.actionBy_Isotope.setText(QCoreApplication.translate("MainWindow", u"By Isotope", None))
        self.actionBy_Energy.setText(QCoreApplication.translate("MainWindow", u"By Energy", None))
        self.actionImport.setText(QCoreApplication.translate("MainWindow", u"Import ...", None))
        self.actionQuadrature.setText(QCoreApplication.translate("MainWindow", u"Quadrature ...", None))
        self.actionX_Aligned_Cylinder.setText(QCoreApplication.translate("MainWindow", u"X-Aligned Cylinder", None))
        self.actionY_Aligned_Cylinder.setText(QCoreApplication.translate("MainWindow", u"Y-Aligned Cylinder", None))
        self.actionZ_Aligned_Cylinder.setText(QCoreApplication.translate("MainWindow", u"Z-Aligned Cylinder", None))
        self.actionFiller_Material.setText(QCoreApplication.translate("MainWindow", u"Filler Material ...", None))
        self.actionQuadrature_2.setText(QCoreApplication.translate("MainWindow", u"Quadrature ...", None))
        self.summaryDescription.setPlaceholderText("")
        self.menu_Source.setTitle(QCoreApplication.translate("MainWindow", u"&Source", None))
        self.menuBody.setTitle(QCoreApplication.translate("MainWindow", u"Body", None))
        self.menuPhotons.setTitle(QCoreApplication.translate("MainWindow", u"Photons", None))
        self.menuShield.setTitle(QCoreApplication.translate("MainWindow", u"Shields", None))
        self.menuAdd.setTitle(QCoreApplication.translate("MainWindow", u"Add", None))
        self.menuDetector.setTitle(QCoreApplication.translate("MainWindow", u"Detector", None))
        self.menuOptions.setTitle(QCoreApplication.translate("MainWindow", u"Options", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
    # retranslateUi

