# Form implementation generated from reading ui file 'OptionsQuadratureDialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(312, 442)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_4.setObjectName("formLayout_4")
        self.triplet1Xname = QtWidgets.QLabel(parent=self.groupBox_2)
        self.triplet1Xname.setObjectName("triplet1Xname")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.triplet1Xname)
        self.triplet1X = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.triplet1X.setObjectName("triplet1X")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.triplet1X)
        self.triplet1Yname = QtWidgets.QLabel(parent=self.groupBox_2)
        self.triplet1Yname.setObjectName("triplet1Yname")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.triplet1Yname)
        self.triplet1Y = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.triplet1Y.setObjectName("triplet1Y")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.triplet1Y)
        self.triplet1Zname = QtWidgets.QLabel(parent=self.groupBox_2)
        self.triplet1Zname.setObjectName("triplet1Zname")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.triplet1Zname)
        self.triplet1Z = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.triplet1Z.setObjectName("triplet1Z")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.triplet1Z)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.triplet1X, self.triplet1Y)
        Dialog.setTabOrder(self.triplet1Y, self.triplet1Z)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Quadrature Specifications"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p>Source Quadrature</p><p>Please enter a preferred source quadrature. Three values represent the quadrature for X, Y, Z (rectangular geometries), R, Theta, Z (cylidrical geometries), and R, Theta, Phi (spherical geometries). Line sources use only the first entry. Point sources do not use quadrature. Default values used by ZapMeNotQt are 10, 10, 10.</p></body></html>"))
        self.groupBox_2.setTitle(_translate("Dialog", "Quadrature Entries"))
        self.triplet1Xname.setText(_translate("Dialog", "First"))
        self.triplet1Yname.setText(_translate("Dialog", "Second"))
        self.triplet1Zname.setText(_translate("Dialog", "Third"))
