# Form implementation generated from reading ui file './OptionsGroupsDialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(323, 189)
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setObjectName("formLayout")
        self.StandardButton = QtWidgets.QRadioButton(parent=Dialog)
        self.StandardButton.setChecked(True)
        self.StandardButton.setObjectName("StandardButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.StandardButton)
        self.ThirtyButton = QtWidgets.QRadioButton(parent=Dialog)
        self.ThirtyButton.setObjectName("ThirtyButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.ThirtyButton)
        self.DiscreteButton = QtWidgets.QRadioButton(parent=Dialog)
        self.DiscreteButton.setObjectName("DiscreteButton")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.DiscreteButton)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.StandardButton.setText(_translate("Dialog", "Standard Groups"))
        self.ThirtyButton.setText(_translate("Dialog", "30 Energy Groups"))
        self.DiscreteButton.setText(_translate("Dialog", "Discrete Photon Energies"))
